apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascent-wow
  labels:
    app: ascent-wow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascent-wow
  template:
    metadata:
      labels:
        app: ascent-wow
    spec:
      containers:
      - name: ascent-wow
        image: docker.io/phazon85/ascent-wow:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        env:
          - name: ASCENT_WOW_TOKEN
            valueFrom:
              secretKeyRef:
                name: discordtoken
                key: token
          - name: ASCENT_WOW_KEYWORD
            valueFrom:
              secretKeyRef:
                name: discordprefix
                key: prefix
          - name: ASCENT_WOW_ENV
            value: "prod"