apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascent-wow
  labels:
    app: ascent-wow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascent-wow
  template:
    metadata:
      labels:
        app: ascent-wow
    spec:
      containers:
      - name: ascent-wow
        image: docker.io/dgparker/ascent-wow
        imagePullPolicy: Always
        ports:
        - containerPort: 443